version: "3.8"
services:
  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    container_name: postgresql
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users
    networks:
      - postgres-compose-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "9991:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge